#!/usr/bin/env php
<?php

use Illuminate\Foundation\Console\Kernel;
use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;

define('LARAVEL_START', microtime(true));

// Autoload dependencies
require __DIR__.'/vendor/autoload.php';

// Bootstrap the application
$app = require __DIR__.'/bootstrap/app.php';

// Create Console Kernel
$kernel = $app->make(Kernel::class);

// Run the command
$status = $kernel->handle(
    $input = new ArgvInput,
    new ConsoleOutput
);

$kernel->terminate($input, $status);

exit($status);
